### ISSUE TITLE
error on invalid manifest names

### ISSUE THREAD

**Issue by hellow554** [cfsamson/tools-cargocleaner#3]
error: failed to parse manifest at `/home/op/projects/barbar/Cargo.toml`

Caused by:
  Invalid character `{` in package name: `{{project-name}}`

```none
cat /home/op/projects/barbar/Cargo.toml
[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

used for [cargo-generate](https://github.com/ashleygwilliams/cargo-generate)

**Comment by cfsamson** [comment]
It should now print a message informing that cleaning failed if `cargo clean` fails and print the error message. It will not panic and exit the program.
